# Generated by Django 2.2.5 on 2020-05-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('elimina', models.BooleanField(default=True)),
            ],
        ),
    ]
