# Generated by Django 2.2.5 on 2020-05-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipopersona', '0002_auto_20200517_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopersona',
            name='fec_car',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tipopersona',
            name='hor_car',
            field=models.DateField(),
        ),
    ]
