# Generated by Django 2.2.5 on 2020-05-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoArma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tipo_arma', models.CharField(max_length=50)),
                ('ind_activo', models.BooleanField(default=True)),
            ],
        ),
    ]
