# Generated by Django 2.2.5 on 2020-05-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actas',
            fields=[
                ('corre_act', models.AutoField(primary_key=True, serialize=False)),
                ('cod_ccp', models.IntegerField(max_length=11)),
                ('cod_est', models.IntegerField(max_length=11)),
                ('num_ofi', models.CharField(max_length=50)),
                ('cod_org', models.IntegerField(max_length=11)),
                ('x', models.CharField(max_length=11)),
                ('y', models.CharField(max_length=11)),
                ('fec_act', models.CharField(max_length=11)),
                ('hora', models.IntegerField(max_length=11)),
                ('minuto', models.IntegerField(max_length=11)),
                ('cod_reg', models.IntegerField(max_length=11)),
                ('cod_mcp', models.IntegerField(max_length=11)),
                ('cod_par', models.IntegerField(max_length=11)),
                ('cod_sec', models.IntegerField(max_length=11)),
                ('cal_ave', models.CharField(max_length=11)),
                ('apt_cas', models.CharField(max_length=11)),
                ('pto_ref', models.CharField(max_length=11)),
                ('usuario', models.CharField(max_length=11)),
                ('opc_car', models.CharField(max_length=11)),
                ('fec_car', models.IntegerField(max_length=11)),
                ('hor_car', models.DateField(auto_now=True)),
                ('elimina', models.CharField(max_length=11)),
            ],
        ),
    ]
