# Generated by Django 2.2.5 on 2020-05-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actas',
            name='cod_ccp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='actas',
            name='cod_est',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='actas',
            name='cod_mcp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='actas',
            name='cod_org',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='actas',
            name='cod_par',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='actas',
            name='cod_reg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='actas',
            name='cod_sec',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='actas',
            name='fec_car',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='actas',
            name='hora',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='actas',
            name='minuto',
            field=models.IntegerField(),
        ),
    ]
